### ISSUE TITLE
can you provide the pretrained model?

### ISSUE THREAD

**Issue by ColdCodeCool** [alpc91/NICE-GAN-pytorch#1]
Thank you for your amazing work, I was wondering if you can provide the pretrained model?

**Comment by ColdCodeCool** [comment]
And another question is how much time did you cost for training NICE-GAN light version and full version respectively?

**Comment by alpc91** [comment]
1. Our previous checkpoint on cat2dog can be downloaded from https://drive.google.com/open?id=1gIA5yhkY71zasY_lXheNjYvphqwhN0Os. 
2.  Due to the limited memory of our NVIDIA RTX 2080Ti GPUs, cost for training light version  is about 80000s for 100K Iters.
