### ISSUE TITLE
test has error

### ISSUE THREAD

**Issue by zjy9779** [alpc91/NICE-GAN-pytorch#11]
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
	size mismatch for FC.0.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 1048576]).

**Comment by alpc91** [comment]
Try：  --light True

**Comment by zjy9779** [comment]
> 
> 
> Try： --light True

it's right
