### ISSUE TITLE
Color disorder when I apply it to generate the license plate 

### ISSUE THREAD

**Issue by stillstream** [alpc91/NICE-GAN-pytorch#14]
![企业微信截图_15995298478073](https://user-images.githubusercontent.com/45909209/92425232-36de3f00-f1b9-11ea-887f-8ec87e5c1494.png)
First, I get the bad result  as above picture when I trained the NICEGAN on various types of license plates.Then, I try to train it on the one of license plates, such as single blue, but the result also is  terrible as the following images.
![image](https://user-images.githubusercontent.com/45909209/92425583-3e521800-f1ba-11ea-8b14-1442523b9628.png)
![image](https://user-images.githubusercontent.com/45909209/92425661-78bbb500-f1ba-11ea-8672-e34ebe79f13f.png)

I wander why this happens? @alpc91

**Comment by alpc91** [comment]
For Color disorder, you can try CycleGAN with identity mapping loss. The identity mapping loss helps preserve the color of the input paintings.  The resconstruction loss in NICE-GAN and identity mapping loss is different. You can add  identity mapping loss in  NICE-GAN.

**Comment by alpc91** [comment]
For Color disorder, you can try CycleGAN with identity mapping loss. The identity mapping loss helps preserve the color of the input paintings.  The resconstruction loss in NICE-GAN and identity mapping loss is different. You can add  identity mapping loss in  NICE-GAN.

**Comment by stillstream** [comment]
Thanks for your reply.
