### ISSUE TITLE
Light version

### ISSUE THREAD

**Issue by neeek2303** [alpc91/NICE-GAN-pytorch#15]
Hello! Could you please clarify what is the "light" version of your network? As I see in issues a lot of people have a problem with training a full version of NICE GAN and use light version. Did you do an experiment with this version? What were the results(metrics)? I could not find this information in your article. Firstly I thought that light = NICE GAN*(are the version that the generator network is composed of only four residual blocks) but after code viewing then I understood that it is not.

**Comment by alpc91** [comment]
For light version, please refer to UGATIT-pytorch.
It means set --light to True and please search "self.light" in networks.py.

**Comment by alpc91** [comment]
> Hello! Could you please clarify what is the "light" version of your network? As I see in issues a lot of people have a problem with training a full version of NICE GAN and use light version. Did you do an experiment with this version? What were the results(metrics)? I could not find this information in your article. Firstly I thought that light = NICE GAN*(are the version that the generator network is composed of only four residual blocks) but after code viewing then I understood that it is not.

For light version, please refer to UGATIT-pytorch.
It means set --light to True and please search "self.light" in networks.py.

**Comment by neeek2303** [comment]
@alpc91 thank you! But did you do experiments with it? How good is it compared to the full version of NICE GAN or UGATIT light (at least approximate metrics)?

**Comment by neeek2303** [comment]
I mean I can try to train in, but it spends a lot of time, and like any other requires parameters tuning and it takes much more time. I want to find out should I spend my time on this or should I concentrate on the full version or UGATIT light.

**Comment by alpc91** [comment]
> @alpc91 thank you! But did you do experiments with it? How good is it compared to the full version of NICE GAN or UGATIT light (at least approximate metrics)?

We have not tested the full version.  If your memory of gpu is sufficient, you can try it. But it will spends much more time.

**Comment by neeek2303** [comment]
@alpc91 Got it! Thank you a lot!
