### ISSUE TITLE
Total iterations 300K or 1000K or 100K?

### ISSUE THREAD

**Issue by veroveroxie** [alpc91/NICE-GAN-pytorch#16]
Hi, thanks for your great work. 

I noticed that your paper uses 100K while the total iteration is set to 300K in the code and UGATIT uses 1000K, which one do you use to train the model?

Thanks!

**Comment by alpc91** [comment]
> Hi, thanks for your great work.
> 
> I noticed that your paper uses 100K while the total iteration is set to 300K in the code and UGATIT uses 1000K, which one do you use to train the model?
> 
> Thanks!
300K, but I have early stopped it.
