### ISSUE TITLE
About the memory of gpu

### ISSUE THREAD

**Issue by mmmll23** [alpc91/NICE-GAN-pytorch#17]
thanks for sharing your good work!
I want to know how big of the gpu memory is enough for training of 256*256 images? I have a 12 G gpu and it seems too small to train even for the light version.

**Comment by Kid-Liet** [comment]
I use Titan RTX (24G), 
the code takes about 20G

**Comment by alpc91** [comment]
CUDA 10.0.130, CuDNN 7.3, and Ubuntu 16.04. NVIDIA GeForce RTX 2080.
I believe that 12 G gpu is enough for training of 256*256 images.


> thanks for sharing your good work!
> I want to know how big of the gpu memory is enough for training of 256*256 images? I have a 12 G gpu and it seems too small to train even for the light version.

**Comment by alpc91** [comment]
> thanks for sharing your good work!
> I want to know how big of the gpu memory is enough for training of 256*256 images? I have a 12 G gpu and it seems too small to train even for the light version.

CUDA 10.0.130, CuDNN 7.3, and Ubuntu 16.04. NVIDIA GeForce RTX 2080.
I believe that 12 G gpu is enough for training of 256*256 images for the light version(--light True).
