### ISSUE TITLE
About the number of parameters of the generator

### ISSUE THREAD

**Issue by Kid-Liet** [alpc91/NICE-GAN-pytorch#18]
Great job！
I would like to quote your paper, but after testing, the number of generator parameters is quite different from that in the paper.
![image](https://user-images.githubusercontent.com/52225942/97828797-163aed00-1d03-11eb-8d08-b7b04c4b3080.png)
Can you tell me what's wrong? I call your code directly

**Comment by alpc91** [comment]
NICE-GAN in the paper refers to light version.
![image](https://user-images.githubusercontent.com/28900189/97832877-df6ad400-1d0e-11eb-8081-7499566d700e.png)
And the full version‘s  is as follows:
![image](https://user-images.githubusercontent.com/28900189/97832957-193bda80-1d0f-11eb-92c0-f0bb71dd34f4.png)


> Great job！
> I would like to quote your paper, but after testing, the number of generator parameters is quite different from that in the paper.
> ![image](https://user-images.githubusercontent.com/52225942/97828797-163aed00-1d03-11eb-8d08-b7b04c4b3080.png)
> Can you tell me what's wrong? I call your code directly

**Comment by alpc91** [comment]
CUDA 10.0.130, CuDNN 7.3, and Ubuntu 16.04.  NVIDIA GeForce RTX 2080

**Comment by Kid-Liet** [comment]
Thank you for your reply. I get it.
