### ISSUE TITLE
如何使用多卡训练这个模型

### ISSUE THREAD

**Issue by BruceYu-Bit** [alpc91/NICE-GAN-pytorch#20]
多卡训练无效

**Comment by alpc91** [comment]
> 多卡训练无效

你可以使用多种多卡训练机制，但是可能需要调整一些超参数，我们并未在这个工作中使用多卡训练，且大多数图像转换模型都是用batchsize为1的训练方式，这或许和GAN的收敛特性有关。但是在我们正在进行的下一个工作中采用了多卡训练，也有合理的结果。
