### ISSUE TITLE
多尺度和 self-attention 是必须的吗？

### ISSUE THREAD

**Issue by TWLemontree** [alpc91/NICE-GAN-pytorch#21]
我们只是想简单的使用您提出的思想，即通过解耦训练来复用判别器网络的编码器部分，但是我们的实验结果不是很理想。我们注意到您的网络中使用了多尺度和自注意力的思想，他们是必须的吗？在您的实验中，去掉这些部分（仅通过最原始的 CycleGAN 网络结构），能跑出不错的结果吗（不追求结果跑的非常好）？

**Comment by alpc91** [comment]
> 我们只是想简单的使用您提出的思想，即通过解耦训练来复用判别器网络的编码器部分，但是我们的实验结果不是很理想。我们注意到您的网络中使用了多尺度和自注意力的思想，他们是必须的吗？在您的实验中，去掉这些部分（仅通过最原始的 CycleGAN 网络结构），能跑出不错的结果吗（不追求结果跑的非常好）？

我们的思想本质上是希望复用判别器编码的特征进行推理，通过使用多尺度和自注意力机制提升了判别器的编码表征，来证明判别器的表征也是可用的，尤其是在继承了强大的判别能力的条件下比自编码器（autoencoder）的表征具有更好的性质。因此你并不一定要使用多尺度和自注意力机制，但是需要保证判别的语义表征足够的好。

**Comment by TWLemontree** [comment]
谢谢您百忙之中的答复，我明白了



在 2021-04-30 11:59:29，"Runfa Chen" ***@***.***> 写道：

我们只是想简单的使用您提出的思想，即通过解耦训练来复用判别器网络的编码器部分，但是我们的实验结果不是很理想。我们注意到您的网络中使用了多尺度和自注意力的思想，他们是必须的吗？在您的实验中，去掉这些部分（仅通过最原始的 CycleGAN 网络结构），能跑出不错的结果吗（不追求结果跑的非常好）？

我们的思想本质上是希望复用判别器编码的特征进行推理，通过使用多尺度和自注意力机制提升了判别器的编码表征，来证明判别器的表征也是可用的，尤其是在继承了强大的判别能力的条件下比自编码器（autoencoder）的表征具有更好的性质。因此你并不一定要使用多尺度和自注意力机制，但是需要保证判别的语义表征足够的好。
