### ISSUE TITLE
请问我训练的模型生成的部分图像有大团的噪点，这个是什么原因呢？

### ISSUE THREAD

**Issue by Q-Zhang98** [alpc91/NICE-GAN-pytorch#25]
![1](https://user-images.githubusercontent.com/94459772/142208469-0b7a59f4-ef0e-4a6b-83db-4992182144a7.png)
![2](https://user-images.githubusercontent.com/94459772/142208480-bb3e9b7b-4955-45d9-977a-ef14fe957580.jpg)

**Comment by alpc91** [comment]
你好，这些现象是伪影，是生成的图片中生成了一些噪声用来欺骗判别器，目前NICE-GAN还不能很好地处理伪影现象。但是随着GAN的发展，近期的工作都很好的克服了伪影的问题，你可以尝试结合近期的改进方法。
