### ISSUE TITLE
Errors on feat. dimension / missing keys in the test script

### ISSUE THREAD

**Issue by naoto0804** [alpc91/NICE-GAN-pytorch#4]
preliminary:
I use PyTorch 1.2.0 (since 1.1.0 throws an error in my environment unfortunately..)
I hope the error is not because of this;

When I try your demo script using the pre-trained model that you provide, 
$ python main.py --dataset cat2dog --phase test
the following error happened. I have two questions;
(i) where do `total_ops` or `total_params` come from?
(ii) Should I use the pre-trained model with `--light True` args?

```
Traceback (most recent call last):
  File "main.py", line 85, in <module>
    main()
  File "main.py", line 81, in main
    gan.test()
  File "/home3/inoue/experiment/im2im/NICE-GAN-pytorch/NICE.py", line 442, in test
    self.load()
  File "/home3/inoue/experiment/im2im/NICE-GAN-pytorch/NICE.py", line 433, in load
    self.gen2B.load_state_dict(params['gen2B'])
  File "/home3/inoue/experiment/im2im/NICE-GAN-pytorch/.env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
        Missing key(s) in state_dict: "total_ops", "total_params", "UpBlock1_1.total_ops", "UpBlock1_1.total_params", "UpBlock1_1.pad1.total_ops", "UpBlock1_1.pad1.total_params", "UpBlock1_1.norm1.total_ops", "UpBlock1_1.norm1.total_params", "UpBlock1_1.pad2.total_ops", "UpBlock1_1.pad2.total_params", "UpBlock1_1.norm2.total_ops", "UpBlock1_1.norm2.total_params", "UpBlock1_2.total_ops", "UpBlock1_2.total_params", "UpBlock1_2.pad1.total_ops", "UpBlock1_2.pad1.total_params", "UpBlock1_2.norm1.total_ops", "UpBlock1_2.norm1.total_params", "UpBlock1_2.pad2.total_ops", "UpBlock1_2.pad2.total_params", "UpBlock1_2.norm2.total_ops", "UpBlock1_2.norm2.total_params", "UpBlock1_3.total_ops", "UpBlock1_3.total_params", "UpBlock1_3.pad1.total_ops", "UpBlock1_3.pad1.total_params", "UpBlock1_3.norm1.total_ops", "UpBlock1_3.norm1.total_params", "UpBlock1_3.pad2.total_ops", "UpBlock1_3.pad2.total_params", "UpBlock1_3.norm2.total_ops", "UpBlock1_3.norm2.total_params", "UpBlock1_4.total_ops", "UpBlock1_4.total_params", "UpBlock1_4.pad1.total_ops", "UpBlock1_4.pad1.total_params", "UpBlock1_4.norm1.total_ops", "UpBlock1_4.norm1.total_params", "UpBlock1_4.pad2.total_ops", "UpBlock1_4.pad2.total_params", "UpBlock1_4.norm2.total_ops", "UpBlock1_4.norm2.total_params", "UpBlock1_5.total_ops", "UpBlock1_5.total_params", "UpBlock1_5.pad1.total_ops", "UpBlock1_5.pad1.total_params", "UpBlock1_5.norm1.total_ops", "UpBlock1_5.norm1.total_params", "UpBlock1_5.pad2.total_ops", "UpBlock1_5.pad2.total_params", "UpBlock1_5.norm2.total_ops", "UpBlock1_5.norm2.total_params", "UpBlock1_6.total_ops", "UpBlock1_6.total_params", "UpBlock1_6.pad1.total_ops", "UpBlock1_6.pad1.total_params", "UpBlock1_6.norm1.total_ops", "UpBlock1_6.norm1.total_params", "UpBlock1_6.pad2.total_ops", "UpBlock1_6.pad2.total_params", "UpBlock1_6.norm2.total_ops", "UpBlock1_6.norm2.total_params", "FC.total_ops", "FC.total_params", "UpBlock0.total_ops", "UpBlock0.total_params", "UpBlock0.0.total_ops", "UpBlock0.0.total_params", "UpBlock0.2.total_ops", "UpBlock0.2.total_params", "UpBlock2.total_ops", "UpBlock2.total_params", "UpBlock2.0.total_ops", "UpBlock2.0.total_params", "UpBlock2.2.total_ops", "UpBlock2.2.total_params", "UpBlock2.5.total_ops", "UpBlock2.5.total_params", "UpBlock2.6.total_ops", "UpBlock2.6.total_params", "UpBlock2.8.total_ops", "UpBlock2.8.total_params", "UpBlock2.10.total_ops", "UpBlock2.10.total_params", "UpBlock2.13.total_ops", "UpBlock2.13.total_params", "UpBlock2.14.total_ops", "UpBlock2.14.total_params", "UpBlock2.16.total_ops", "UpBlock2.16.total_params", "UpBlock2.18.total_ops", "UpBlock2.18.total_params".
        size mismatch for FC.0.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 1048576]).
```

**Comment by prettyshy** [comment]
> preliminary:
> I use PyTorch 1.2.0 (since 1.1.0 throws an error in my environment unfortunately..)
> I hope the error is not because of this;
> 
> When I try your demo script using the pre-trained model that you provide,
> $ python main.py --dataset cat2dog --phase test
> the following error happened. I have two questions;
> (i) where do `total_ops` or `total_params` come from?
> (ii) Should I use the pre-trained model with `--light True` args?
> 
> ```
> Traceback (most recent call last):
>   File "main.py", line 85, in <module>
>     main()
>   File "main.py", line 81, in main
>     gan.test()
>   File "/home3/inoue/experiment/im2im/NICE-GAN-pytorch/NICE.py", line 442, in test
>     self.load()
>   File "/home3/inoue/experiment/im2im/NICE-GAN-pytorch/NICE.py", line 433, in load
>     self.gen2B.load_state_dict(params['gen2B'])
>   File "/home3/inoue/experiment/im2im/NICE-GAN-pytorch/.env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
>         Missing key(s) in state_dict: "total_ops", "total_params", "UpBlock1_1.total_ops", "UpBlock1_1.total_params", "UpBlock1_1.pad1.total_ops", "UpBlock1_1.pad1.total_params", "UpBlock1_1.norm1.total_ops", "UpBlock1_1.norm1.total_params", "UpBlock1_1.pad2.total_ops", "UpBlock1_1.pad2.total_params", "UpBlock1_1.norm2.total_ops", "UpBlock1_1.norm2.total_params", "UpBlock1_2.total_ops", "UpBlock1_2.total_params", "UpBlock1_2.pad1.total_ops", "UpBlock1_2.pad1.total_params", "UpBlock1_2.norm1.total_ops", "UpBlock1_2.norm1.total_params", "UpBlock1_2.pad2.total_ops", "UpBlock1_2.pad2.total_params", "UpBlock1_2.norm2.total_ops", "UpBlock1_2.norm2.total_params", "UpBlock1_3.total_ops", "UpBlock1_3.total_params", "UpBlock1_3.pad1.total_ops", "UpBlock1_3.pad1.total_params", "UpBlock1_3.norm1.total_ops", "UpBlock1_3.norm1.total_params", "UpBlock1_3.pad2.total_ops", "UpBlock1_3.pad2.total_params", "UpBlock1_3.norm2.total_ops", "UpBlock1_3.norm2.total_params", "UpBlock1_4.total_ops", "UpBlock1_4.total_params", "UpBlock1_4.pad1.total_ops", "UpBlock1_4.pad1.total_params", "UpBlock1_4.norm1.total_ops", "UpBlock1_4.norm1.total_params", "UpBlock1_4.pad2.total_ops", "UpBlock1_4.pad2.total_params", "UpBlock1_4.norm2.total_ops", "UpBlock1_4.norm2.total_params", "UpBlock1_5.total_ops", "UpBlock1_5.total_params", "UpBlock1_5.pad1.total_ops", "UpBlock1_5.pad1.total_params", "UpBlock1_5.norm1.total_ops", "UpBlock1_5.norm1.total_params", "UpBlock1_5.pad2.total_ops", "UpBlock1_5.pad2.total_params", "UpBlock1_5.norm2.total_ops", "UpBlock1_5.norm2.total_params", "UpBlock1_6.total_ops", "UpBlock1_6.total_params", "UpBlock1_6.pad1.total_ops", "UpBlock1_6.pad1.total_params", "UpBlock1_6.norm1.total_ops", "UpBlock1_6.norm1.total_params", "UpBlock1_6.pad2.total_ops", "UpBlock1_6.pad2.total_params", "UpBlock1_6.norm2.total_ops", "UpBlock1_6.norm2.total_params", "FC.total_ops", "FC.total_params", "UpBlock0.total_ops", "UpBlock0.total_params", "UpBlock0.0.total_ops", "UpBlock0.0.total_params", "UpBlock0.2.total_ops", "UpBlock0.2.total_params", "UpBlock2.total_ops", "UpBlock2.total_params", "UpBlock2.0.total_ops", "UpBlock2.0.total_params", "UpBlock2.2.total_ops", "UpBlock2.2.total_params", "UpBlock2.5.total_ops", "UpBlock2.5.total_params", "UpBlock2.6.total_ops", "UpBlock2.6.total_params", "UpBlock2.8.total_ops", "UpBlock2.8.total_params", "UpBlock2.10.total_ops", "UpBlock2.10.total_params", "UpBlock2.13.total_ops", "UpBlock2.13.total_params", "UpBlock2.14.total_ops", "UpBlock2.14.total_params", "UpBlock2.16.total_ops", "UpBlock2.16.total_params", "UpBlock2.18.total_ops", "UpBlock2.18.total_params".
>         size mismatch for FC.0.weight: copying a param with shape torch.Size([256, 256]) from checkpoint, the shape in current model is torch.Size([256, 1048576]).
> ```

use --light True during test. I meet the same problem and use this have solved it.

**Comment by naoto0804** [comment]
@prettyshy Thanks, so nice to hear that!
