### ISSUE TITLE
Use NICE as a plug-in startegy into current I2I models.

### ISSUE THREAD

**Issue by ddlee-cn** [alpc91/NICE-GAN-pytorch#6]
Very nice work!

I wonder whether that the NICE strategy can be used as a plug-in component into current I2I models like UNIT or DRIT. Did you observe any improvements when replacing the encoders in these models with its discriminators?

**Comment by alpc91** [comment]
We haven't done specific experiments in diverse-output translation, but think it will bring improvement, you can try it. We are applying it to other applications and network architecture.
