### ISSUE TITLE
关于 cam_loss

### ISSUE THREAD

**Issue by Decalogue** [alpc91/NICE-GAN-pytorch#8]
您好!
我看到代码里有 cam_loss 但是论文中没有提到.在 UGATIT 中这个 loss 的比例是1000,请问您代码里的比例是10吗?我看代码里没有单独设置权重,而是统一使用的 adv_weight.
谢谢!

**Comment by alpc91** [comment]
cam_loss 在论文里指的是C0_x local scale的gan loss，其中用了UGATIT的cam注意力机制，同时加上了residual。local、middle、global的gan loss目前都是统一使用的 adv_weight=10，可以根据实际任务，调节各个尺度的loss权重比例。
